services:
  frontend:
    image: ghcr.io/jspaste/frontend:latest
    container_name: jspaste-frontend
    ports:
      - "127.0.0.1:60000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - ./.env.frontend
    security_opt:
      - no-new-privileges:true

  backend:
    image: ghcr.io/jspaste/backend:latest
    container_name: jspaste-backend
    ports:
      - "127.0.0.1:60001:4000"
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - ./.env.backend
    volumes:
      - jspaste-backend-data:/home/nonroot/documents
    security_opt:
      - no-new-privileges:true

volumes:
  jspaste-backend-data: