services:
  frontend:
    image: ghcr.io/jspaste/frontend:latest
    container_name: frontend
    ports:
      - "127.0.0.1:60000:3000"
    env_file:
      - ./.env.frontend
    security_opt:
      - no-new-privileges:true

  backend:
    image: ghcr.io/jspaste/backend:latest
    container_name: backend
    ports:
      - "127.0.0.1:60001:4000"
    env_file:
      - ./.env.backend
    volumes:
      - backend-data:/home/nonroot/documents
    security_opt:
      - no-new-privileges:true

volumes:
  backend-data: